# Generated by Django 4.2.3 on 2023-07-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0002_alter_trade_options_remove_trade_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rock_name', models.CharField(max_length=30, verbose_name='Название камня')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
            },
        ),
        migrations.AddField(
            model_name='trade',
            name='rock_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapi.rock', verbose_name='Купленый камень'),
        ),
    ]
