# Generated by Django 4.2.3 on 2023-07-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0003_rock_trade_rock_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='rock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapi.rock', verbose_name='Купленый камень'),
        ),
    ]
