# Generated by Django 4.2.3 on 2023-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0004_alter_trade_rock_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_spent',
            field=models.FloatField(null=True, verbose_name='Траты за все время'),
        ),
    ]
